myapp_accueil:
  pattern: /
  defaults: { _controller: MyAppGdaBundle:Default:index }    
myapp_anomalie_lister:
  pattern: /anomalie/
  defaults: { _controller: MyAppGdaBundle:Anomalie:lister }
myapp_anomalie_creer:
  pattern: /anomalie/creer
  defaults: { _controller: MyAppGdaBundle:Anomalie:creer }
myapp_anomalie_modifier:
  pattern: /anomalie/modifier/{id}
  defaults: { _controller: MyAppGdaBundle:Anomalie:modifier }
myapp_anomalie_supprimer:
  pattern: /anomalie/supprimer/{id}
  defaults: { _controller: MyAppGdaBundle:Anomalie:supprimer }
myapp_anomalie_merdique:
  pattern: /anomalie/supprimer/{id}
  defaults: { _controller: MyAppGdaBundle:Anomalie:supprimer }