parameters:
#    my_app_gda.example.class: MyApp\GdaBundle\Example

services:
#    my_app_gda.example:
#        class: %my_app_gda.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
